---
  - name: Mount Citrix Virtual Applications and Desktops ISO
    win_shell: |
      $mountResult = Mount-DiskImage -ImagePath '{{ cvad_license_iso_location }}\{{ cvad_license_iso_file }}'
      $driveLetter = ($mountResult | Get-Volume).DriveLetter
      return $driveLetter
    register: mounted_iso_drive_letter
    changed_when: false
    become: yes

  - name: "Install Citrix License Server from CVAD {{ cvad_license_version }} ISO"
    win_package:
      path: "{{ mounted_iso_drive_letter.stdout[0] }}:\\{{ cvad_license_install_file_location }}\\{{ cvad_license_install_file }}"
      product_id: "{{ cvad_license_product_id }}"
      arguments: "{{ cvad_license_install_arguments }}"
      state: "{{ cvad_license_install_state }}"

  - name: Dismount Citrix Virtual Applications and Desktops ISO
    win_shell: Dismount-DiskImage -ImagePath '{{ cvad_license_iso_location }}\{{ cvad_license_iso_file }}'
    changed_when: false
    become: yes
