---
galaxy_info:
  role_name: run_citrix_optimizer
  author: Joe Shonk
  description: Run Citrix Optimizer
  company: The Shonk Project

  license: GPL-3.0-only

  min_ansible_version: 2.9

  platforms:
   - name: Windows
     versions:
     - All

  galaxy_tags:
    - citrix
    - cvad
    - vda
    - citrixoptimizer
    - optimizations
    - optimizer
