---
  cvad_delivery_controller_versions:
    1912 LTSR CU2:
      iso_file: Citrix_Virtual_Apps_and_Desktops_7_1912_2000.iso
      install_arguments: /components controller,desktopstudio /configure_firewall /nosql /noreboot /quiet
      product_id: '{65568E93-FF7E-4CF4-88C8-8EF288D92EB1}'
    1912 LTSR CU3:
      iso_file: Citrix_Virtual_Apps_and_Desktops_7_1912_3000.iso
      install_arguments: /components controller,desktopstudio /configure_firewall /nosql /noreboot /quiet
      product_id: '{99E67721-8766-432A-83C2-1E55ED5517F3}'
    2012:
      iso_file: Citrix_Virtual_Apps_and_Desktops_7_2012.iso
      install_arguments: /components controller,desktopstudio /configure_firewall /nosql /noreboot /quiet
      product_id: '{DD56A91F-F623-4917-B229-C9BE2DFC7925}'
    2103:
      iso_file: Citrix_Virtual_Apps_and_Desktops_7_2103.iso
      install_arguments: /components controller,desktopstudio /configure_firewall /nosql /noreboot /quiet
      product_id: '{07EBAA9B-5D49-4C86-9571-834F4BE05FA8}'

  smb_location: \\file1\automation

# Options
# 1912 LTSR CU2
# 1912 LTSR CU3
# 2012
# 2103
  cvad_delivery_controller_version: 1912 LTSR CU3
  cvad_delivery_controller_iso_location: "{{ smb_location }}\\Citrix\\Citrix Virtual Apps and Desktops\\{{ cvad_delivery_controller_version }}"
  cvad_delivery_controller_iso_file: "{{ cvad_delivery_controller_versions[cvad_delivery_controller_version].iso_file }}"
  cvad_delivery_controller_install_file_location: x64\XenDesktop Setup
  cvad_delivery_controller_install_file: XenDesktopServerSetup.exe
  cvad_delivery_controller_install_arguments: "{{ cvad_delivery_controller_versions[cvad_delivery_controller_version].install_arguments }}"
  cvad_delivery_controller_product_id: "{{ cvad_delivery_controller_versions[cvad_delivery_controller_version].product_id }}"
  cvad_delivery_controller_install_state: present

  # Set to import_and_bind or do_not_import_and_bind
  cvad_delivery_controller_import_and_bind_pfx_certificate: import_and_bind
  cvad_delivery_controller_certificate_name: wildcard2021
