---
  - name: Mount Citrix Virtual Applications and Desktops ISO
    win_shell: |
      $mountResult = Mount-DiskImage -ImagePath '{{ cvad_delivery_controller_iso_location }}\{{ cvad_delivery_controller_iso_file }}'
      $driveLetter = ($mountResult | Get-Volume).DriveLetter
      return $driveLetter
    register: mounted_iso_drive_letter
    changed_when: false
    become: yes

  - name: "Install Citrix Delivery Controller from CVAD {{ cvad_delivery_controller_version }} ISO"
    win_package:
      path: "{{ mounted_iso_drive_letter.stdout[0] }}:\\{{ cvad_delivery_controller_install_file_location }}\\{{ cvad_delivery_controller_install_file }}"
      product_id: "{{ cvad_delivery_controller_product_id }}"
      arguments: "{{ cvad_delivery_controller_install_arguments }}"
      state: "{{ cvad_delivery_controller_install_state }}"
    notify: Bind Certificate to Citrix Broker Service

  - name: Dismount Citrix Virtual Applications and Desktops ISO
    win_shell: Dismount-DiskImage -ImagePath '{{ cvad_delivery_controller_iso_location }}\{{ cvad_delivery_controller_iso_file }}'
    changed_when: false
    become: yes

  - name: Flush Handlers
    meta: flush_handlers
