---
galaxy_info:
  role_name: install_license_iso
  author: Joe Shonk
  description: Install the Citrix License Server from an .ISO file mounted from an SMB share
  company: The Shonk Project

  license: GPL-3.0-only

  min_ansible_version: 2.9

  platforms:
   - name: Windows
     versions:
     - 2016
     - 2019

  galaxy_tags:
    - citrix
    - cvad
    - license
