---
  cvad_session_recording_agent_versions:
    1912 LTSR CU2:
      iso_file: Citrix_Virtual_Apps_and_Desktops_7_1912_2000.iso
      product_id: '{5C31D558-520E-4060-9A26-F4E87F52E822}'
    1912 LTSR CU3:
      iso_file: Citrix_Virtual_Apps_and_Desktops_7_1912_3000.iso
      product_id: '{8F34D86E-E683-46B9-859A-60FD2699632A}'
    2012:
      iso_file: Citrix_Virtual_Apps_and_Desktops_7_2012.iso
      product_id: '{9B3DEC67-CE4B-4170-8EF7-1D29DAFEE151}'
    2103:
      iso_file: Citrix_Virtual_Apps_and_Desktops_7_2103.iso
      product_id: '{7b0519a9-3c5c-4c54-85f7-26498bfe6b44}'

  cvad_session_recording_agent_servername: myservername.mycompany.com
  cvad_session_recording_agent_broker_protocol: HTTPS
  cvad_session_recording_agent_broker_port: 443

  smb_location: \\file1\automation

# Options
#  1912 LTSR CU2
#  1912 LTSR CU3
#  2012
#  2103
  cvad_session_recording_agent_version: 1912 LTSR CU3
  cvad_session_recording_agent_iso_location: "{{ smb_location }}\\Citrix\\Citrix Virtual Apps and Desktops\\{{ cvad_session_recording_agent_version }}"
  cvad_session_recording_agent_iso_file: "{{ cvad_session_recording_agent_versions[cvad_session_recording_agent_version].iso_file }}"
  cvad_session_recording_agent_install_file_location: x64\Session Recording
  cvad_session_recording_agent_install_file: SessionRecordingAgentx64.msi
  cvad_session_recording_agent_install_arguments: "/qn SESSIONRECORDINGSERVERNAME={{ cvad_session_recording_agent_servername }} SESSIONRECORDINGBROKERPROTOCOL={{ cvad_session_recording_agent_broker_protocol }} SESSIONRECORDINGBROKERPORT={{ cvad_session_recording_agent_broker_port }}"
  cvad_session_recording_agent_product_id: "{{ cvad_session_recording_agent_versions[cvad_session_recording_agent_version].product_id }}"
  cvad_session_recording_agent_install_state: present
