---
  - name: Mount Citrix Virtual Applications and Desktops ISO
    win_shell: |
      $mountResult = Mount-DiskImage -ImagePath '{{ cvad_director_iso_location }}\{{ cvad_director_iso_file }}'
      $driveLetter = ($mountResult | Get-Volume).DriveLetter
      return $driveLetter
    register: mounted_iso_drive_letter
    changed_when: false
    become: yes

  - name: "Install Citrix Director from CVAD {{ cvad_director_version }} ISO"
    win_package:
      path: "{{ mounted_iso_drive_letter.stdout[0] }}:\\{{ cvad_director_install_file_location }}\\{{ cvad_director_install_file }}"
      product_id: "{{ cvad_director_product_id }}"
      arguments: "{{ cvad_director_install_arguments }}"
      state: "{{ cvad_director_install_state }}"

  - name: Dismount Citrix Virtual Applications and Desktops ISO
    win_shell: Dismount-DiskImage -ImagePath '{{ cvad_director_iso_location }}\{{ cvad_director_iso_file }}'
    changed_when: false
    become: yes

  - name: Bind Certificate to IIS for Citrix Director
    win_iis_webbinding:
      name: Default Web Site
      protocol: https
      port: 443
      ip: '*'
      certificate_hash: "{{ certificates[cvad_director_certificate_name].certificate_pfx_thumbprint }}"
      state: present
    when: cvad_director_import_and_bind_pfx_certificate == 'import_and_bind'
